language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"

script: mvn -Dskip.surefire.tests=false -Dskip.failsafe.tests=false verify

after_success:
- bash <(curl -s https://codecov.io/bash)

